# Generated by Django 4.1.2 on 2022-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profesion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
