# Generated by Django 4.1.2 on 2022-11-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_email_user_servicio_detalle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Servs',
        ),
    ]
