# Generated by Django 4.1.2 on 2022-11-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_servs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servs',
            name='edad',
        ),
    ]
