# Generated by Django 4.1.2 on 2022-11-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_servs_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servs',
            name='fecha_nacimiento',
        ),
    ]
