# Generated by Django 4.1.2 on 2022-11-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_servs_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servs',
            name='servicio_detalle',
        ),
    ]
