# Generated by Django 4.1.2 on 2022-11-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_servs_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servs',
            name='servicio_ofrecido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
